# Generated by Django 5.0.6 on 2024-05-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0003_basecustomer_remove_customer_firstname_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity of ordered item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commons.orderitem', verbose_name='Order item')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order containing this item')),
            ],
        ),
    ]
