# Generated by Django 5.0.6 on 2024-05-26 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(verbose_name='State/Province')),
                ('city', models.CharField(verbose_name='City')),
                ('streetAddress', models.CharField(verbose_name='Street Address')),
                ('streetAddress2', models.CharField(verbose_name='Extra info on Street Address(Street Address 2)')),
                ('postCode', models.CharField(verbose_name='Post Code')),
                ('note', models.CharField(verbose_name='Note for delivery, instructions etc')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(verbose_name='Label for item')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(verbose_name='First Name')),
                ('lastName', models.CharField(verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(verbose_name='Phone number')),
                ('billingAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.address')),
            ],
        ),
    ]
