# Generated by Django 5.0.6 on 2024-05-26 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
    ]
