# Generated by Django 5.0.6 on 2024-05-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20240526_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(verbose_name='First Name')),
                ('lastName', models.CharField(verbose_name='Last Name')),
                ('phone', models.CharField(verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'BaseCustomer',
                'verbose_name_plural': 'BaseCustomers',
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='isShopifyOrderItem',
            field=models.BooleanField(default=False, verbose_name='Is the order item from the shopify list?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='basecustomer_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commons.basecustomer'),
            preserve_default=False,
        ),
    ]
