# Generated by Django 5.0.6 on 2024-05-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_basecustomer_remove_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecustomer',
            options={},
        ),
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
        migrations.AlterModelTable(
            name='basecustomer',
            table='base-customers',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order-items',
        ),
    ]
