# Generated by Django 5.0.6 on 2024-05-26 20:10

import django.db.models.deletion
import src.commons.enums.fulfillment_status_enum
import src.commons.enums.order_method_enum
import src.commons.enums.order_status_enum
import src.commons.enums.payment_status_enum
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0003_basecustomer_remove_customer_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedAt', models.DateField(verbose_name='When was the order recorded')),
                ('fulfilledAt', models.DateField(verbose_name='When was the order fulfilled at')),
                ('takenBy', models.CharField(verbose_name='Employee name who took the order')),
                ('method', models.CharField(choices=src.commons.enums.order_method_enum.OrderMethodEnum.choices(), verbose_name='Order method')),
                ('fulfillmentDate', models.DateTimeField(verbose_name='When is the deadline to fulfill the order')),
                ('paymentStatus', models.CharField(choices=src.commons.enums.payment_status_enum.PaymentStatusEnum.choices(), verbose_name='Payment Status of the order')),
                ('fulfillmentStatus', models.CharField(choices=src.commons.enums.fulfillment_status_enum.FulfillmentStatusEnum.choices(), verbose_name='Fulfillment Status of the order')),
                ('content', models.TextField(verbose_name='Content of the order, Free text')),
                ('totalOrderCost', models.PositiveBigIntegerField(verbose_name='Total Cost of the order including delivery charges')),
                ('itemsCost', models.PositiveBigIntegerField(verbose_name='Total Cost of the order items combined excluding delivery charges')),
                ('orderStatus', models.CharField(choices=src.commons.enums.order_status_enum.OrderStatusEnum.choices(), verbose_name='Order status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer', to='commons.customer', verbose_name='Customer for this order')),
                ('deliveryAddress', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='commons.address', verbose_name='Delivery Address for the order')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Recipient', to='commons.basecustomer', verbose_name='Recipient details')),
            ],
        ),
    ]
