# Generated by Django 5.0.6 on 2024-05-26 20:10

import django.db.models.deletion
import src.commons.enums.notification_type_enum
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Notification text')),
                ('type', models.CharField(choices=src.commons.enums.notification_type_enum.NotificationTypeEnum.choices(), verbose_name='Notification type')),
                ('viewed', models.BooleanField(default=False, verbose_name='Is notification seen ?')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_by', to=settings.AUTH_USER_MODEL, verbose_name='Who performed the action which caused the notification')),
            ],
        ),
    ]
