# Generated by Django 5.0.6 on 2024-05-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgotpasswordtoken',
            options={},
        ),
        migrations.AlterModelTable(
            name='forgotpasswordtoken',
            table='forgot-password-token',
        ),
    ]
